# Generated by Django 5.1.15 on 2026-03-25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("family", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationShareSetting",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sharing_enabled", models.BooleanField(default=True)),
                (
                    "share_precision",
                    models.CharField(
                        choices=[("exact", "Exact"), ("approximate", "Approximate")],
                        default="exact",
                        max_length=20,
                    ),
                ),
                (
                    "history_retention_hours",
                    models.PositiveIntegerField(
                        default=168,
                        validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(720)],
                    ),
                ),
                (
                    "live_visibility_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(720)],
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="location_share_settings", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={"db_table": "location_share_settings"},
        ),
        migrations.CreateModel(
            name="UserGeofence",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("center_latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("center_longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "radius_m",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(5000)]
                    ),
                ),
                ("notify_on_enter", models.BooleanField(default=True)),
                ("notify_on_exit", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="geofences", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={"db_table": "user_geofences", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="UserLocationPing",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("accuracy_m", models.FloatField(blank=True, null=True)),
                ("altitude_m", models.FloatField(blank=True, null=True)),
                ("speed_kmh", models.FloatField(blank=True, null=True)),
                ("heading_deg", models.FloatField(blank=True, null=True)),
                (
                    "battery_level",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                ("is_charging", models.BooleanField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("gps", "GPS"), ("network", "Network"), ("passive", "Passive"), ("manual", "Manual")],
                        default="gps",
                        max_length=20,
                    ),
                ),
                ("is_mocked", models.BooleanField(default=False)),
                ("recorded_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="location_pings", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "db_table": "user_location_pings",
                "ordering": ["-recorded_at"],
                "indexes": [models.Index(fields=["user", "-recorded_at"], name="user_locatio_user_id_e6f418_idx"), models.Index(fields=["recorded_at"], name="user_locatio_recorde_e9bc53_idx")],
            },
        ),
        migrations.CreateModel(
            name="GeofenceEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(choices=[("enter", "Enter"), ("exit", "Exit")], max_length=10)),
                ("distance_m", models.FloatField(blank=True, null=True)),
                ("occurred_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "geofence",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="location.usergeofence"),
                ),
                (
                    "ping",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="geofence_events", to="location.userlocationping"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="geofence_events", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "db_table": "geofence_events",
                "ordering": ["-occurred_at"],
                "indexes": [models.Index(fields=["user", "-occurred_at"], name="geofence_ev_user_id_b7e5df_idx"), models.Index(fields=["geofence", "-occurred_at"], name="geofence_ev_geofenc_e87e37_idx")],
            },
        ),
        migrations.CreateModel(
            name="FamilyLocationPermission",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("can_view_live", models.BooleanField(default=True)),
                ("can_view_history", models.BooleanField(default=True)),
                ("can_view_battery", models.BooleanField(default=True)),
                ("can_view_speed", models.BooleanField(default=True)),
                (
                    "history_window_hours",
                    models.PositiveIntegerField(
                        default=24,
                        validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)],
                    ),
                ),
                (
                    "precision_mode",
                    models.CharField(
                        choices=[("inherit", "Inherit"), ("exact", "Exact"), ("approximate", "Approximate")],
                        default="inherit",
                        max_length=20,
                    ),
                ),
                (
                    "family_link",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="location_permission", to="family.familylink"),
                ),
            ],
            options={"db_table": "family_location_permissions"},
        ),
    ]
