# Generated by Django 5.1.15 on 2026-03-25 12:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="geofenceevent",
            new_name="geofence_ev_user_id_11d184_idx",
            old_name="geofence_ev_user_id_b7e5df_idx",
        ),
        migrations.RenameIndex(
            model_name="geofenceevent",
            new_name="geofence_ev_geofenc_585c20_idx",
            old_name="geofence_ev_geofenc_e87e37_idx",
        ),
        migrations.RenameIndex(
            model_name="userlocationping",
            new_name="user_locati_user_id_8269bc_idx",
            old_name="user_locatio_user_id_e6f418_idx",
        ),
        migrations.RenameIndex(
            model_name="userlocationping",
            new_name="user_locati_recorde_57fa3b_idx",
            old_name="user_locatio_recorde_e9bc53_idx",
        ),
    ]
