# Generated by Django 5.1.15 on 2026-04-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("family", "0002_add_family_group_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="plan",
            field=models.CharField(
                choices=[("free", "Free"), ("plus", "Plus"), ("premium", "Premium")],
                default="free",
                help_text="Subscription plan (free/plus/premium)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="family",
            name="max_members",
            field=models.PositiveIntegerField(default=4),
        ),
    ]
