# Generated by Django 5.1.15 on 2026-04-11 20:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sos_alerts", models.BooleanField(default=True)),
                ("medication_reminders", models.BooleanField(default=True)),
                ("health_updates", models.BooleanField(default=True)),
                ("family_messages", models.BooleanField(default=True)),
                ("appointment_reminders", models.BooleanField(default=True)),
                ("activity_goals", models.BooleanField(default=True)),
                ("notification_sound", models.BooleanField(default=True)),
                ("notification_vibration", models.BooleanField(default=True)),
                ("quiet_hours_enabled", models.BooleanField(default=False)),
                (
                    "quiet_hours_start",
                    models.TimeField(default="22:00", help_text="HH:MM format"),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(default="08:00", help_text="HH:MM format"),
                ),
                ("quiet_hours_exception_emergency", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
                "db_table": "notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("sos_alert", "SOS Alert"),
                            ("medication_reminder", "Medication Reminder"),
                            ("health_update", "Health Update"),
                            ("family_message", "Family Message"),
                            ("appointment_reminder", "Appointment Reminder"),
                            ("activity_goal", "Activity Goal"),
                            ("emergency", "Emergency"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("action", models.CharField(blank=True, default="", max_length=100)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("opened", models.BooleanField(default=False)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="notificatio_user_id_611c58_idx",
                    ),
                    models.Index(
                        fields=["user", "read"], name="notificatio_user_id_1f75db_idx"
                    ),
                ],
            },
        ),
    ]
