# Generated by Django 5.1.15 on 2026-03-08 11:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WellnessTip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(help_text="Short summary shown in the card"),
                ),
                (
                    "content",
                    models.TextField(blank=True, help_text="Full article / details"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("nutrition", "Nutrition"),
                            ("exercise", "Exercise"),
                            ("meditation", "Meditation"),
                            ("ayurveda", "Ayurveda"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Ionicons icon name", max_length=30
                    ),
                ),
                (
                    "duration",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Duration in minutes (for timers, e.g. meditation)",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Lower = shown first"
                    ),
                ),
            ],
            options={
                "verbose_name": "Wellness Tip",
                "verbose_name_plural": "Wellness Tips",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TipInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("favorite", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("favorited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tip_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="gyaan.wellnesstip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tip Interaction",
                "verbose_name_plural": "Tip Interactions",
                "unique_together": {("user", "tip")},
            },
        ),
    ]
