# Generated by Django 5.1.15 on 2026-03-08 10:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "dosage",
                    models.CharField(
                        blank=True, help_text="e.g., 500mg, 1 tablet", max_length=100
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("once_daily", "Once Daily"),
                            ("twice_daily", "Twice Daily"),
                            ("thrice_daily", "Thrice Daily"),
                            ("four_times", "Four Times Daily"),
                            ("as_needed", "As Needed"),
                            ("weekly", "Weekly"),
                            ("custom", "Custom"),
                        ],
                        default="once_daily",
                        max_length=20,
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Special instructions like 'take with food'",
                    ),
                ),
                (
                    "schedule_times",
                    models.CharField(
                        default="08:00",
                        help_text="Comma-separated times in HH:MM format, e.g., '08:00,14:00,20:00'",
                        max_length=100,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("reminder_enabled", models.BooleanField(default=True)),
                (
                    "reminder_minutes_before",
                    models.PositiveSmallIntegerField(default=15),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Label for this prescription", max_length=200
                    ),
                ),
                ("doctor_name", models.CharField(blank=True, max_length=150)),
                ("hospital_name", models.CharField(blank=True, max_length=200)),
                ("prescription_date", models.DateField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="prescriptions/%Y/%m/"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("pdf", "PDF"),
                            ("other", "Other"),
                        ],
                        default="image",
                        max_length=10,
                    ),
                ),
                (
                    "file_url",
                    models.URLField(
                        blank=True,
                        help_text="External URL if not uploaded",
                        max_length=500,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-prescription_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicineIntake",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("scheduled_date", models.DateField()),
                ("scheduled_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("taken", "Taken"),
                            ("missed", "Missed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intakes",
                        to="medicine.medicine",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_date", "-scheduled_time"],
                "unique_together": {("medicine", "scheduled_date", "scheduled_time")},
            },
        ),
    ]
