# Generated by Django 5.1.15 on 2026-04-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicine", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="current_quantity",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of pills/doses currently in stock",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="medicine",
            name="doses_per_day",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="How many doses/pills the user takes per day (auto-derived from schedule_times count)",
            ),
        ),
    ]
