# Generated by Django 5.1.15 on 2026-03-08 09:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reading_type",
                    models.CharField(
                        choices=[
                            ("bp", "Blood Pressure"),
                            ("sugar", "Blood Sugar"),
                            ("weight", "Weight"),
                            ("heartRate", "Heart Rate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("min_value", models.FloatField(blank=True, null=True)),
                ("max_value", models.FloatField(blank=True, null=True)),
                ("target_value", models.FloatField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Goal",
                "verbose_name_plural": "Health Goals",
                "db_table": "health_goals",
                "unique_together": {("user", "reading_type")},
            },
        ),
        migrations.CreateModel(
            name="HealthReading",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reading_type",
                    models.CharField(
                        choices=[
                            ("bp", "Blood Pressure"),
                            ("sugar", "Blood Sugar"),
                            ("weight", "Weight"),
                            ("heartRate", "Heart Rate"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("value", models.CharField(max_length=50)),
                ("value_primary", models.FloatField(blank=True, null=True)),
                ("value_secondary", models.FloatField(blank=True, null=True)),
                ("unit", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("warning", "Warning"),
                            ("danger", "Danger"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("recorded_at", models.DateTimeField(db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_readings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Reading",
                "verbose_name_plural": "Health Readings",
                "db_table": "health_readings",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "reading_type", "-recorded_at"],
                        name="health_read_user_id_def937_idx",
                    ),
                    models.Index(
                        fields=["user", "-recorded_at"],
                        name="health_read_user_id_dea3ee_idx",
                    ),
                ],
            },
        ),
    ]
