# Generated by Django 5.1.15 on 2026-03-08 10:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "specialty",
                    models.CharField(
                        choices=[
                            ("general", "General Physician"),
                            ("cardiologist", "Cardiologist"),
                            ("diabetologist", "Diabetologist"),
                            ("neurologist", "Neurologist"),
                            ("orthopedic", "Orthopedic"),
                            ("dermatologist", "Dermatologist"),
                            ("gynecologist", "Gynecologist"),
                            ("pediatrician", "Pediatrician"),
                            ("psychiatrist", "Psychiatrist"),
                            ("ophthalmologist", "Ophthalmologist"),
                            ("ent", "ENT Specialist"),
                            ("other", "Other"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("hospital", models.CharField(blank=True, max_length=200)),
                ("address", models.TextField(blank=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Personal notes about this doctor"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Mark as primary care physician"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "name"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "doctor_name",
                    models.CharField(
                        help_text="Stored in case doctor is deleted", max_length=200
                    ),
                ),
                ("specialty", models.CharField(blank=True, max_length=50)),
                ("appointment_date", models.DateField()),
                ("appointment_time", models.TimeField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("missed", "Missed"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Post-appointment notes"),
                ),
                ("reminder_sent", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to="doctor.doctor",
                    ),
                ),
            ],
            options={
                "ordering": ["-appointment_date", "-appointment_time"],
            },
        ),
        migrations.CreateModel(
            name="MedicalDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("prescription", "Prescription"),
                            ("lab_report", "Lab Report"),
                            ("scan", "Medical Scan"),
                            ("xray", "X-Ray"),
                            ("discharge_summary", "Discharge Summary"),
                            ("insurance", "Insurance Document"),
                            ("vaccination", "Vaccination Record"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "document_date",
                    models.DateField(help_text="Date of the document/report"),
                ),
                (
                    "file",
                    models.FileField(blank=True, upload_to="medical_documents/%Y/%m/"),
                ),
                (
                    "file_url",
                    models.URLField(
                        blank=True, help_text="External URL if not uploaded"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="doctor.appointment",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="doctor.doctor",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-document_date"],
            },
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(
                fields=["user", "-is_primary"], name="doctor_doct_user_id_a58c23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(
                fields=["user", "specialty"], name="doctor_doct_user_id_cc4962_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["user", "-appointment_date"],
                name="doctor_appo_user_id_3edf60_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["user", "status"], name="doctor_appo_user_id_1e19e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicaldocument",
            index=models.Index(
                fields=["user", "-document_date"], name="doctor_medi_user_id_e09337_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicaldocument",
            index=models.Index(
                fields=["user", "document_type"], name="doctor_medi_user_id_c2c7bf_idx"
            ),
        ),
    ]
